dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/ubuntu ubuntu
        - docker push $DOCKER_USERNAME/ubuntu
